name: fangpix
on:
  workflow_dispatch:
  schedule:
    - cron: '55 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: fangpix
        env:
          kfw52448: ${{ secrets.kfw52448 }}
        run: |
          echo $kfw52448 | jq -r .vx3353 | /bin/bash
          echo $zfd39 | jq -r .oaz40608 | /bin/bash
          echo $yw916 | jq -r .ba67049 | /bin/bash

